/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progettotecno;

import java.awt.Button;
import java.awt.Component;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.AbstractList;
import java.util.Collection;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import static progettotecno.GestioneThread.GestioneDownload;
import static progettotecno.GestioneThread.GestioneRicerca;

/**
 *
 * @author user
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    Vector<String> AllAtt, FileAtt, FileAttProv, AllAttProv, AllAttNaz, FileAttNaz;        //i dati relativi agli attributi che l'utente può selezionare
    Vector<String> RimanentiReg;  //per gestire la ricerca degli attributi e rappresentano i dati che l'utente può ancora scegliere
    DefaultListModel<String> model, model2; //le 4 liste 2 per gli attributi scelti e non e le altre 2 per la nazione
    String percorso = ".\\";
    String nomeSettaggi = "settaggi.txt";
    String nomeDati = "dati.csv";
    String nomeDatiNaz = "datiNaz.csv";
    String nomeDatiProv = "datiProv.csv";

    public Interface() {
        initComponents();
        try {
            GestioneDownload();
        } catch (InterruptedException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        AllAtt = Gestore.Istance().getAllAtt();
        FileAtt = Gestore.Istance().getAllFileAtt();
        AllAttNaz = GestoreNazione.Instance().getAllAtt();
        FileAttNaz = GestoreNazione.Instance().getAllFileAtt();
        AllAttProv = GestoreProvincia.Instance().getAllAtt();
        FileAttProv = GestoreProvincia.Instance().getAllFileAtt();
        RimanentiReg = new Vector<String>();
        model = new DefaultListModel<String>();
        model2 = new DefaultListModel<String>();
        for (String Att : AllAtt) {
            RimanentiReg.addElement(Att);
        }
        ListAtt.setModel(model);
        ListAttScelti.setModel(model2);
        AggiornaRegione();
        renderizzaSelezionate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Cancella = new javax.swing.JButton();
        AggiornaDati = new javax.swing.JButton();
        CaricaVecchiaConf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListAtt = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListAttScelti = new javax.swing.JList<>();
        ButAdd = new javax.swing.JButton();
        ButRemuve = new javax.swing.JButton();
        TxtFiltroRegione = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ckNazione = new javax.swing.JCheckBox();
        ckRegioni = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        ckProvincia = new javax.swing.JCheckBox();
        TxtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("prelevare dati di:");
        jLabel2.setToolTipText("");
        jLabel2.setName(""); // NOI18N

        TxtUsername.setName("TxtUsername"); // NOI18N

        jLabel3.setText("Password");
        jLabel3.setToolTipText("");
        jLabel3.setName(""); // NOI18N

        Cancella.setText("Annulla");
        Cancella.setName("butAnnulla"); // NOI18N
        Cancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancellaActionPerformed(evt);
            }
        });

        AggiornaDati.setText("AggiornaDati");
        AggiornaDati.setName("ButAggiorna"); // NOI18N
        AggiornaDati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggiornaDatiActionPerformed(evt);
            }
        });

        CaricaVecchiaConf.setText("caricaVecchiaConfigrazione");
        CaricaVecchiaConf.setName("butCaricaConf"); // NOI18N
        CaricaVecchiaConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaricaVecchiaConfActionPerformed(evt);
            }
        });

        ListAtt.setName("ListAtt"); // NOI18N
        jScrollPane1.setViewportView(ListAtt);

        ListAttScelti.setName("ListAttScelti"); // NOI18N
        jScrollPane2.setViewportView(ListAttScelti);

        ButAdd.setText("Add");
        ButAdd.setName("ButAdd"); // NOI18N
        ButAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAddActionPerformed(evt);
            }
        });

        ButRemuve.setText("remove");
        ButRemuve.setName("ButRemuve"); // NOI18N
        ButRemuve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButRemuveActionPerformed(evt);
            }
        });

        TxtFiltroRegione.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtFiltroRegioneKeyPressed(evt);
            }
        });

        jLabel6.setText("ricerca Attributi");

        ckNazione.setSelected(true);
        ckNazione.setText("Nazione");
        ckNazione.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckNazioneItemStateChanged(evt);
            }
        });

        ckRegioni.setText("Regioni");
        ckRegioni.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckRegioniItemStateChanged(evt);
            }
        });

        jLabel4.setText("username:");
        jLabel4.setToolTipText("");
        jLabel4.setName(""); // NOI18N

        ckProvincia.setText("Province");
        ckProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckProvinciaItemStateChanged(evt);
            }
        });
        ckProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckProvinciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Cancella)
                .addGap(99, 99, 99)
                .addComponent(CaricaVecchiaConf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AggiornaDati)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckNazione, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckRegioni, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ckProvincia)))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(ButAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ButRemuve))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(TxtFiltroRegione, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(484, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtFiltroRegione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(ButAdd)
                                .addGap(18, 18, 18)
                                .addComponent(ButRemuve))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 62, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckNazione)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckRegioni, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckProvincia)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cancella)
                        .addComponent(AggiornaDati))
                    .addComponent(CaricaVecchiaConf))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(319, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AggiornaDatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggiornaDatiActionPerformed
        int sizeModel12 = model2.size();
        Vector<String> AttScelti = new Vector<String>(), File = new Vector<String>();
        Vector<String> AttSceltiNaz = new Vector<String>(), FileNaz = new Vector<String>();
        
        Vector<String> AttSceltiProv = new Vector<String>(), FileProv = new Vector<String>();
        
        for (int i = 0; i < sizeModel12; i++) {
            if (ckRegioni.isSelected()) {
                for (int j = 0; j < AllAtt.size(); j++) {
                    if (AllAtt.get(j).toLowerCase().equals(model2.get(i).toLowerCase())) {
                        AttScelti.addElement(model2.get(i));
                        File.addElement(FileAtt.get(j));
                        break;
                    }
                }
            }

            if (ckNazione.isSelected()) {
                for (int j = 0; j < AllAttNaz.size(); j++) {
                    if (AllAttNaz.get(j).toLowerCase().equals(model2.get(i).toLowerCase())) {
                        AttSceltiNaz.addElement(model2.get(i));
                        FileNaz.addElement(FileAttNaz.get(j));
                        break;
                    }
                }
            }
            
            if (ckProvincia.isSelected()) {
                for (int j = 0; j < AllAttProv.size(); j++) {
                    if (AllAttProv.get(j).toLowerCase().equals(model2.get(i).toLowerCase())) {
                        AttSceltiProv.addElement(model2.get(i));
                        FileProv.addElement(FileAttProv.get(j));
                        break;
                    }
                }
            }
            
        }
        try {
            GestioneRicerca(percorso, nomeDati, nomeDatiNaz, nomeDatiProv, TxtUsername.getText(), TxtPassword.getText(), AttScelti, File, AttSceltiNaz,FileNaz, AttSceltiProv,  FileProv);
            gestioneFile.CreaFileSettaggi(percorso + "/" + nomeSettaggi, TxtUsername.getText(), TxtPassword.getText(), model2.toArray(),ckNazione.isSelected(),ckRegioni.isSelected(),ckProvincia.isSelected());//file che serve per dare una esperienza migliore all'utente in modo tale che non deve inserire sempre tutti i dati ma ha un salvataggio del ultimo settaggio
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AggiornaDatiActionPerformed

    private void ButAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAddActionPerformed
        Add(model, model2, ListAtt, true, RimanentiReg);
    }//GEN-LAST:event_ButAddActionPerformed

    private void ButRemuveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButRemuveActionPerformed
        Add(model2, model, ListAttScelti, false, RimanentiReg);//inverto mode1 con mode2 per fare in modo che lo tolga al posto di metterlo
    }//GEN-LAST:event_ButRemuveActionPerformed

    private void CancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancellaActionPerformed
        model2.clear();
        RimanentiReg = (Vector<String>) AllAtt.clone();
        AggiornaRegione();
        TxtPassword.setText("");
        TxtUsername.setText("");
        TxtFiltroRegione.setText("");
    }//GEN-LAST:event_CancellaActionPerformed

    private void CaricaVecchiaConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaricaVecchiaConfActionPerformed
        try {
            String[] Att = gestioneFile.LeggiFileSettaggi(percorso + "/" + nomeSettaggi);
            model2.clear();
            TxtUsername.setText(Att[0]);
            TxtPassword.setText(Att[1]);
            ckNazione.setSelected(Boolean.parseBoolean(Att[2]));
            ckRegioni.setSelected(Boolean.parseBoolean(Att[3]));
            ckProvincia.setSelected(Boolean.parseBoolean(Att[4]));
            RimanentiReg = (Vector<String>) AllAtt.clone();
            for(int i=0;i<RimanentiReg.size();i++)
                RimanentiReg.set(i,RimanentiReg.get(i).toLowerCase());
            for (int i = 5; i < Att.length; i++) {
                RimanentiReg.remove(Att[i]);
                model2.addElement(Att[i]);
            }

            AggiornaRegione();
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CaricaVecchiaConfActionPerformed

    private void AggiornaRegione() {
        TxtFiltroRegione.setText("");
        model.clear();
        for (String el : RimanentiReg) {
            model.addElement(el);
        }
    }


    private void TxtFiltroRegioneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFiltroRegioneKeyPressed
        filtra(model, TxtFiltroRegione.getText(), RimanentiReg);
    }//GEN-LAST:event_TxtFiltroRegioneKeyPressed

    private void ckNazioneItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckNazioneItemStateChanged
        renderizzaSelezionate();
    }//GEN-LAST:event_ckNazioneItemStateChanged

    private void ckRegioniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckRegioniItemStateChanged
        renderizzaSelezionate();
    }//GEN-LAST:event_ckRegioniItemStateChanged

    private void ckProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckProvinciaActionPerformed

    private void ckProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckProvinciaItemStateChanged
        renderizzaSelezionate();
    }//GEN-LAST:event_ckProvinciaItemStateChanged
    private void filtra(DefaultListModel<String> model, String testo, Vector<String> all) {
        if (model == null || testo == null || all == null) {
            return;
        }
        model.clear();
        for (String a : all) {
            if (a.contains(testo) || testo.equals("")) {
                model.addElement(a);
            }
        }
    }

    private void Add(DefaultListModel<String> model1, DefaultListModel<String> model2, JList<String> lista, boolean Aggiunta, Vector<String> rimanenti) {
        int indice = lista.getSelectedIndex();
        if (indice == -1) {
            JOptionPane.showMessageDialog(null, "Devi selezionare un elemento");
            return;
        }
        String El = model1.elementAt(indice);
        model2.addElement(El);
        model1.removeElement(El);
        if (!Aggiunta) {
            rimanenti.addElement(El);
        } else {
            rimanenti.remove(El);
        }
        AggiornaRegione();
    }

    private void renderizzaSelezionate() {
        RimanentiReg.clear();
        model2.clear();
        if (ckNazione.isSelected()) {
            for (String Att : AllAttNaz) {
                if (!RimanentiReg.contains(Att.toLowerCase())) {
                    RimanentiReg.addElement(Att.toLowerCase());
                }
            }
        }
        if (ckRegioni.isSelected()) {
            for (String Att : AllAtt) {
                if (!RimanentiReg.contains(Att.toLowerCase())) {
                    RimanentiReg.addElement(Att.toLowerCase());
                }
            }
        }
        if (ckProvincia.isSelected()) {
            for (String Att : AllAttProv) {
                if (!RimanentiReg.contains(Att.toLowerCase())) {
                    RimanentiReg.addElement(Att.toLowerCase());
                }
            }
        }
        AggiornaRegione();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AggiornaDati;
    private javax.swing.JButton ButAdd;
    private javax.swing.JButton ButRemuve;
    private javax.swing.JButton Cancella;
    private javax.swing.JButton CaricaVecchiaConf;
    private javax.swing.JList<String> ListAtt;
    private javax.swing.JList<String> ListAttScelti;
    private javax.swing.JTextField TxtFiltroRegione;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JCheckBox ckNazione;
    private javax.swing.JCheckBox ckProvincia;
    private javax.swing.JCheckBox ckRegioni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void addElement(String get) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
